language: ruby
sudo: false
cache: bundler
bundler_args: --without yard guard benchmarks

before_install:
  - gem install bundler -v '~> 1.10'

env:
  - rails=4.2.0
  - rails=5.0.0.rc1

rvm:
  - 2.1
  - 2.2.4
  - 2.3.0
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head